{% set version = "1.0.0post0" %}

package:
  name: micro_sam
  version: {{ version }}

source:
  url: https://github.com/computational-cell-analytics/micro-sam/archive/v{{ version }}.tar.gz
  sha256: 89aa423ddc069e64cf08c5066fecb8fc894ed063a694bcd579f28fe7bb7bb4d0

build:
  entry_points:
    - micro_sam.annotator_2d = micro_sam.sam_annotator.annotator_2d:main
    - micro_sam.annotator_3d = micro_sam.sam_annotator.annotator_3d:main
    - micro_sam.annotator_tracking = micro_sam.sam_annotator.annotator_tracking:main
    - micro_sam.image_series_annotator = micro_sam.sam_annotator.image_series_annotator:main
    - micro_sam.precompute_embeddings = micro_sam.precompute_state:main
  noarch: python
  number: 1
  script: pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - kornia
    - napari >=0.4.18
    - pooch
    - pyqt
    - python >=3.8
    - python-elf >=0.4.8
    - python-xxhash
    - pytorch
    - segment-anything
    - torchvision
    - torch_em >=0.7.1
    - tqdm
    - timm
    - zarr

test:
  imports:
    - micro_sam
  source_files:
    - test/**/*.py
  commands:
    - python -m unittest discover -s test -v

about:
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Segment Anything for Microscopy.
  home: https://github.com/computational-cell-analytics/micro-sam

extra:
  recipe-maintainers:
    - constantinpape
